### ISSUE TITLE
install on a droplet

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/bot#3]
We now have a [script](https://github.com/gratipay/gratipay-gremlin/blob/4d94b07dd4ae08701a33020848dd3de423583f4c/rotate-radar.py) to rotate the radar. Let's deploy it!

I'm thinking we can spin up another droplet at Digital Ocean for this, and use `cron`.

**Comment by chadwhitacre** [comment]
I wrote a [script](https://github.com/gratipay/bot/blob/e45bcf76597933a484adb52aff08eb0d79bd072f/start-payday.py) to kick off payday. My hope and dream is to run it under cron at Digital Ocean tomorrow.

**Comment by chadwhitacre** [comment]
I've spun up a droplet. I need to configure keys so I can access it.

**Comment by chadwhitacre** [comment]
Progress!

```
Mar  3 11:47:01 bot CRON[10832]: (root) CMD (/root/bot/update.sh | logger -t bot)
Mar  3 11:47:01 bot bot: Up-to-date

Mar  3 11:48:01 bot CRON[10913]: (root) CMD (/root/bot/update.sh | logger -t bot)
Mar  3 11:48:01 bot bot: Updating ...
Mar  3 11:48:03 bot bot: Updating 4e36d47..96fb7b5
Mar  3 11:48:03 bot bot: Fast-forward
Mar  3 11:48:03 bot bot:  README.md | 3 +--
Mar  3 11:48:03 bot bot:  crontab   | 6 +++---
Mar  3 11:48:03 bot bot:  update.sh | 3 ++-
Mar  3 11:48:03 bot bot:  3 files changed, 6 insertions(+), 6 deletions(-)
Mar  3 11:48:03 bot bot: Requirement already up-to-date: requests==2.9.1 in ./env/lib/python3.4/site-packages (from -r requirements.txt (line 1))
Mar  3 11:48:03 bot crontab[10955]: (root) REPLACE (root)

Mar  3 11:49:01 bot CRON[10957]: (root) CMD (/root/bot/update.sh | logger -t UPDATE-BOT)
```

**Comment by chadwhitacre** [comment]
Now I need to configure environment variables and I'm ready to test out payday!

**Comment by chadwhitacre** [comment]
```
Mar  3 12:20:01 bot CRON[11578]: (root) CMD ($PYTHON /root/bot/kick-off-payday.py 2>&1 | logger -t KICK-OFF-PAYDAY)
Mar  3 12:20:01 bot CRON[11579]: (root) CMD ($PYTHON /root/bot/rotate-radar.py 2>&1 | logger -t ROTATE-RADAR)
Mar  3 12:20:01 bot CRON[11580]: (root) CMD (/root/bot/update.sh 2>&1 | logger -t UPDATE-BOT)
Mar  3 12:20:03 bot ROTATE-RADAR: created https://github.com/gratipay-bot/test/issues/10
Mar  3 12:20:03 bot ROTATE-RADAR: closed https://github.com/gratipay-bot/test/issues/4
Mar  3 12:20:03 bot KICK-OFF-PAYDAY: created https://github.com/gratipay-bot/test/issues/11
```

:flushed:

**Comment by chadwhitacre** [comment]
Blam!

![screen shot 2016-03-03 at 12 21 04 pm](https://cloud.githubusercontent.com/assets/134455/13502798/775335de-e13a-11e5-8099-97d4f7150df1.png)
![screen shot 2016-03-03 at 12 21 12 pm](https://cloud.githubusercontent.com/assets/134455/13502797/7750535a-e13a-11e5-8d4d-72e6d475c418.png)

**Comment by chadwhitacre** [comment]
https://github.com/gratipay-bot/test/issues/10

https://github.com/gratipay-bot/test/issues/11

**Comment by chadwhitacre** [comment]
Okay! I'm about ready to aim this at gratipay/inside.gratipay.com.

**Comment by chadwhitacre** [comment]
Alright! So what are the steps here? I've made sure that the tickets have the content we want to be copied over to the new tickets. Here's my plan:
- [x] take out the testing cron jobs—done in 40a6df05270a36c4590eb4ddc0db749e37fc4a38
- [x] redeploy to make sure README is right
- [x] modify the configuration
- [x] modify cron to run payday now—done in 8f5243f7cb7192fd721f270752873be42b85be7d and 3165f4c3802ad6112e730889ded4f11d65d015ba
- [x] watch @gratipay-bot kick off payday!
- [x] modify cron to run payday Thursday early—done in 903b68a1391c07dd14a0ee33bd9d866e3fd50cc3

**Comment by chadwhitacre** [comment]
```
root@bot:~/bot# tail -f /var/log/syslog
Mar  3 13:42:01 bot CRON[2918]: (root) CMD (/root/bot/update-if-needed.sh 2>&1 | logger -t UPDATE-BOT)
Mar  3 13:42:02 bot UPDATE-BOT: From https://github.com/gratipay/bot
Mar  3 13:42:02 bot UPDATE-BOT:    cc4e14b..8f5243f  master     -> origin/master
Mar  3 13:42:02 bot UPDATE-BOT: Here we go!
Mar  3 13:42:02 bot UPDATE-BOT: Updating cc4e14b..8f5243f
Mar  3 13:42:02 bot UPDATE-BOT: Fast-forward
Mar  3 13:42:02 bot UPDATE-BOT:  crontab | 2 +-
Mar  3 13:42:02 bot UPDATE-BOT:  1 file changed, 1 insertion(+), 1 deletion(-)
Mar  3 13:42:03 bot UPDATE-BOT: Requirement already up-to-date: requests==2.9.1 in ./env/lib/python3.4/site-packages (from -r requirements.txt (line 1))
Mar  3 13:42:03 bot crontab[2972]: (root) REPLACE (root)


Mar  3 13:43:01 bot cron[918]: (root) RELOAD (crontabs/root)
Mar  3 13:43:01 bot CRON[2977]: (root) CMD (/root/bot/update-if-needed.sh 2>&1 | logger -t UPDATE-BOT)
Mar  3 13:44:01 bot CRON[2990]: (root) CMD (/root/bot/update-if-needed.sh 2>&1 | logger -t UPDATE-BOT)
Mar  3 13:45:01 bot CRON[3004]: (root) CMD ($PYTHON /root/bot/kick-off-payday.py 2>&1 | logger -t KICK-OFF-PAYDAY)
Mar  3 13:45:01 bot CRON[3005]: (root) CMD (/root/bot/update-if-needed.sh 2>&1 | logger -t UPDATE-BOT)
Mar  3 13:45:02 bot KICK-OFF-PAYDAY: Traceback (most recent call last):
Mar  3 13:45:02 bot KICK-OFF-PAYDAY:   File "/root/bot/kick-off-payday.py", line 43, in <module>
Mar  3 13:45:02 bot KICK-OFF-PAYDAY:     main()
Mar  3 13:45:02 bot KICK-OFF-PAYDAY:   File "/root/bot/kick-off-payday.py", line 38, in main
Mar  3 13:45:02 bot KICK-OFF-PAYDAY:     previous = paydays.find_previous()
Mar  3 13:45:02 bot KICK-OFF-PAYDAY:   File "/root/bot/kick-off-payday.py", line 11, in find_previous
Mar  3 13:45:02 bot KICK-OFF-PAYDAY:     return self.hit_api('get', params={'state': 'all', 'labels': 'Payday'})[0]
Mar  3 13:45:02 bot KICK-OFF-PAYDAY:   File "/root/bot/botlib.py", line 37, in hit_api
Mar  3 13:45:02 bot KICK-OFF-PAYDAY:     raise APIError(response.status_code, response.text)
Mar  3 13:45:02 bot KICK-OFF-PAYDAY: botlib.APIError: <APIError 404: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}>
```

**Comment by chadwhitacre** [comment]
Indeed, I had `GITHUB_REPO` wrong (`gratipay-bot/inside.gratipay.com` instead of `gratipay/inside.gratipay.com`). Fixed now, modifying crontab again ...

**Comment by chadwhitacre** [comment]
Picked up the new crontab:

```
Mar  3 13:46:01 bot CRON[3021]: (root) CMD (/root/bot/update-if-needed.sh 2>&1 | logger -t UPDATE-BOT)
Mar  3 13:47:01 bot CRON[3106]: (root) CMD (/root/bot/update-if-needed.sh 2>&1 | logger -t UPDATE-BOT)
Mar  3 13:48:02 bot CRON[3121]: (root) CMD (/root/bot/update-if-needed.sh 2>&1 | logger -t UPDATE-BOT)
Mar  3 13:48:02 bot UPDATE-BOT: From https://github.com/gratipay/bot
Mar  3 13:48:02 bot UPDATE-BOT:    8f5243f..3165f4c  master     -> origin/master
Mar  3 13:48:02 bot UPDATE-BOT: Here we go!
Mar  3 13:48:03 bot UPDATE-BOT: Updating 8f5243f..3165f4c
Mar  3 13:48:03 bot UPDATE-BOT: Fast-forward
Mar  3 13:48:03 bot UPDATE-BOT:  crontab | 2 +-
Mar  3 13:48:03 bot UPDATE-BOT:  1 file changed, 1 insertion(+), 1 deletion(-)
Mar  3 13:48:03 bot UPDATE-BOT: Requirement already up-to-date: requests==2.9.1 in ./env/lib/python3.4/site-packages (from -r requirements.txt (line 1))
Mar  3 13:48:03 bot crontab[3174]: (root) REPLACE (root)
```

**Comment by chadwhitacre** [comment]
```

Mar  3 13:50:01 bot CRON[3190]: (root) CMD ($PYTHON /root/bot/kick-off-payday.py 2>&1 | logger -t KICK-OFF-PAYDAY)
Mar  3 13:50:01 bot CRON[3191]: (root) CMD (/root/bot/update-if-needed.sh 2>&1 | logger -t UPDATE-BOT)
Mar  3 13:50:03 bot KICK-OFF-PAYDAY: created https://github.com/gratipay/inside.gratipay.com/issues/526
```

:flushed:

**Comment by chadwhitacre** [comment]
https://github.com/gratipay/inside.gratipay.com/issues/526

!m @gratipay-bot :dancer:

**Comment by chadwhitacre** [comment]
https://twitter.com/Gratipay/status/705466509733199872
